The complete explanation for this notebook is at https://youranalystbuddy.com/array-concatenation/

## Array dimensionality

In [1]:
import numpy as np

### one-dimensional

In [2]:
array1d = np.array([4,5,6,1,3])
array1d.shape

(5,)

### two-dimensional

In [3]:
array2d = np.array([
    [4,6,6],
    [1,8,2]
])
array2d.shape

(2, 3)

### three-dimensional

In [4]:
array3d = np.array([
    [
        [4,5,8],
        [5,1,3],
        [8,2,0]
    ],
    [
        [3,1,8],
        [9,5,3],
        [1,2,3]
    ],
])
array3d.shape

(2, 3, 3)

## 1D array concatenation

In [5]:
array1 = np.array([1,6,2,4])
array2 = np.array([4,2])
array3 = np.array([9,6,3])
np.concatenate([array1, array2, array3])

array([1, 6, 2, 4, 4, 2, 9, 6, 3])

## 2D array concatenation

### Horizontally

In [6]:
array1 = np.array([
    [1,7,3,4],
    [2,1,6,5],
    [8,9,4,3]
])
array1.shape

(3, 4)

In [7]:
array2 = np.array([
    [5,6],
    [3,2],
    [8,8]
])
array2.shape

(3, 2)

In [8]:
np.concatenate([array1, array2], axis=1)

array([[1, 7, 3, 4, 5, 6],
       [2, 1, 6, 5, 3, 2],
       [8, 9, 4, 3, 8, 8]])

### Vertically

In [9]:
array1 = np.array([
    [3,5,1,8],
    [2,6,4,9],
])
array1.shape

(2, 4)

In [10]:
array2 = np.array([
    [9,1,1,3],
    [5,4,5,6],
    [6,2,1,1]
])
array2.shape

(3, 4)

In [11]:
np.concatenate([array1, array2], axis=0)

array([[3, 5, 1, 8],
       [2, 6, 4, 9],
       [9, 1, 1, 3],
       [5, 4, 5, 6],
       [6, 2, 1, 1]])