The complete explanation for this notebook is at https://youranalystbuddy.com/numpy-operations/

## Mathematical operations on numpy arrays

In [1]:
import numpy as np

an_array = np.array([1, 5, 4, 9 ,7])

In [2]:
an_array + 10

array([11, 15, 14, 19, 17])

In [3]:
an_array - 5

array([-4,  0, -1,  4,  2])

In [4]:
an_array ** 2

array([ 1, 25, 16, 81, 49])

### Comparison operations

In [5]:
an_array > 5

array([False, False, False,  True,  True])

In [6]:
an_array < 5

array([ True, False,  True, False, False])

In [14]:
an_array == 5

array([False,  True, False, False, False])

## Elementwise operations

In [7]:
array_2 = np.array([
    [2,5,6,1,2],
    [6,3,1,3,6]
])

In [8]:
array_2 + an_array

array([[ 3, 10, 10, 10,  9],
       [ 7,  8,  5, 12, 13]])

In [19]:
array1 = np.array([5,1,8,6,2])
array2 = np.array([7,4,3,0,5])

In [20]:
array1 + array2

array([12,  5, 11,  6,  7])

In [21]:
array1 * array2

array([35,  4, 24,  0, 10])

In [22]:
array1 > array2

array([False, False,  True,  True, False])

## Numpy functions

In [40]:
an_array = np.array([6,4,3,5,2])

In [43]:
np.log(an_array)

array([1.79175947, 1.38629436, 1.09861229, 1.60943791, 0.69314718])

In [44]:
np.sin(an_array)

array([-0.2794155 , -0.7568025 ,  0.14112001, -0.95892427,  0.90929743])

In [46]:
np.sum(an_array)

20

In [47]:
np.mean(an_array)

4.0

In [48]:
np.median(an_array)

4.0

In [49]:
np.var(an_array)

2.0

In [50]:
np.std(an_array)

1.4142135623730951

### Applying with axis

In [54]:
data = np.array([
    [3, 20, 100, 392],
    [2, 14, 89, 453],
    [5, 11, 153, 412],
    [1, 24, 121, 312],
    [3, 22, 90, 431]
])

In [55]:
np.mean(data, axis=0)

array([  2.8,  18.2, 110.6, 400. ])

In [56]:
np.mean(data, axis=1)

array([128.75, 139.5 , 145.25, 114.5 , 136.5 ])

## Example in data analysis

In [57]:
gpas = np.array([
    [3.12, 3.31, 3.54],
    [2.57, 2.59, 2.55],
    [2.39, 2.78, 3.11],
    [3.21, 2.91, 2.73],
    [3.52, 3.55, 3.62]
])

In [62]:
print('means of GPAs:', gpas.mean(axis=0))
print('standard deviations of GPAs:',gpas.std(axis=0))

means of GPAs: [2.962 3.028 3.11 ]
standard deviations of GPAs: [0.41920878 0.35193181 0.42497059]


In [63]:
gpas[:,1] - gpas[:,0]

array([ 0.19,  0.02,  0.39, -0.3 ,  0.03])

In [65]:
gpas[:,2] - gpas[:,1]

array([ 0.23, -0.04,  0.33, -0.18,  0.07])

In [66]:
np.log(gpas)

array([[1.137833  , 1.19694819, 1.26412673],
       [0.9439059 , 0.95165788, 0.93609336],
       [0.87129337, 1.02245093, 1.13462273],
       [1.16627094, 1.06815308, 1.00430161],
       [1.25846099, 1.2669476 , 1.28647403]])