The complete explanation for this notebook is at https://youranalystbuddy.com/numpy-arrays/

## Motivation

Working with data without dedicated containers is inconvenient

In [1]:
employees = [
    [100320,36,5,110000],
    [132201,30,3,105000],
    [100212,45,12,133000],
    [143695,27,1,80000]
]

for employee in employees:
    print(employee)

[100320, 36, 5, 110000]
[132201, 30, 3, 105000]
[100212, 45, 12, 133000]
[143695, 27, 1, 80000]


In [3]:
age = []

for row in employees:
    age.append(row[1])

print(age)

[36, 30, 45, 27]


In [4]:
sum(age) / len(age)

34.5

## Basic Numpy arrays

In [5]:
import numpy as np

In [6]:
employees = np.array([
    [100320,36,5,110000],
    [132201,30,3,105000],
    [100212,45,12,133000],
    [143695,27,1,80000]
])

employees

array([[100320,     36,      5, 110000],
       [132201,     30,      3, 105000],
       [100212,     45,     12, 133000],
       [143695,     27,      1,  80000]])

In [7]:
employees.shape

(4, 4)

### Slicing Numpy arrays

In [11]:
employees[0]

array([100320,     36,      5, 110000])

In [10]:
employees[[0,3]]

array([[100320,     36,      5, 110000],
       [143695,     27,      1,  80000]])

In [12]:
employees[:,0]

array([100320, 132201, 100212, 143695])

In [13]:
employees[:,[1,3]]

array([[    36, 110000],
       [    30, 105000],
       [    45, 133000],
       [    27,  80000]])

In [14]:
employees[:3,[1,3]]

array([[    36, 110000],
       [    30, 105000],
       [    45, 133000]])

### Slicing with conditions

In [16]:
employees[employees[:,1] > 30]

array([[100320,     36,      5, 110000],
       [100212,     45,     12, 133000]])

In [17]:
employees[employees[:,-1] < 110000]

array([[132201,     30,      3, 105000],
       [143695,     27,      1,  80000]])